// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decode(arg1) {
  return window['go']['codec']['Codec']['Decode'](arg1);
}

export function Encode(arg1) {
  return window['go']['codec']['Codec']['Encode'](arg1);
}
