// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decode(arg1:string):Promise<string>;

export function Encode(arg1:string):Promise<string>;
