// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function About() {
  return window['go']['main']['App']['About']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}
